### ISSUE TITLE
win11中cmd运行时出现编码错误问题

### ISSUE THREAD

**Issue by Frzgunr1** [MZhao-ouo/CMDGPT#2]
![image](https://user-images.githubusercontent.com/87064639/228559839-d7f113a4-0fa0-4e0b-9d58-fe10d51fc37b.png)

如图所示

**Comment by MZhao-ouo** [comment]
换成powershell或者试试用windows terminal

**Comment by Frzgunr1** [comment]
已解决，应当是编码问题，windows terminal可行
