### ISSUE TITLE
credit 报错，其余正常

### ISSUE THREAD

**Issue by qiaoborui** [MZhao-ouo/CMDGPT#4]
![image](https://user-images.githubusercontent.com/39862938/229362227-4f794379-656c-48ab-baf2-38e551a5b2d2.jpeg)

**Comment by MZhao-ouo** [comment]
嘶，看起来是这个API被封了，我看看有没有解决办法

**Comment by qiaoborui** [comment]
嗯嗯，辛苦了，给个star😆

**Comment by MZhao-ouo** [comment]
已经解决，解决方法是删除credit的功能。但可以用usage看用量
